\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{pset_d}[2015/12/13 Arun Debray's problem set template]
% I decided to split my pset template into a class because:
%	- my pset template is currently duplicated with each new math class I take; and
%	- that code is intermixed with macros that affect my lecture notes.
% Thus, on this relatively big revision of my template, I might as well ensure that I centralize everything and
% organize it.

% Some package options
% 1. Option `boldsets' replaces \mathbb N, Z, Q, R, ... with \mathbf. `bbsets` (default) uses \mathbb.
\DeclareOption{boldsets}{\newcommand{\m@thbb}{\mathbf}}
\DeclareOption{bbsets}{\newcommand{\m@thbb}{\mathbb}
% 2. Option `rmdiff' (default) typesets the d in \int f(x) dx upright; `itdiff` sets it in italic.
\DeclareOption{rmdiff}{\newcommand{\df@nt}{\mathrm}}
\DeclareOption{itdiff}{\newcommand{\df@nt}{\mathnormal}
% 3. Option `thminenum' (default) numbers theorems inside problem numbers, e.g. Theorem 27.1; `thmalone' numbers
% them independently, e.g. Theorem 1.
\DeclareOption{thminenum}{\def\thm@enum{}}
\DeclareOption{thmalone}{}
% 4. Option `eqninenum' numbers equations inside problem numbers, e.g. (27.1); `eqnsymbol' (default) tags them with
% dingbats, e.g. (*), (§), etc.
\DeclareOption{eqninenum}{\def\eqn@enum{}}
\DeclareOption{eqnalone}{}
% 5. Option 'onesided' places a header on each page; `twosided' (default) on each odd-numbered page.
\DeclareOption{onesided}{\def\@nesided{}}
\DeclareOption{twosided}{}

% Other options can be handed off to the amsart class (e.g. fontsize)
\DeclareOption*{\PassOptionsToClass{\CurrentOption}{amsart}}

\ExecuteOptions{bbsets, rmdiff, thminenum, eqnalone, twosided}
\ProcessOptions\relax

\LoadClass[reqno]{amsart}

% This allows us to use characters like é and ö directly, rather than having to write \'e and \"o
\RequirePackage[utf8]{inputenc}

% Sets the margin.
\RequirePackage[margin=0.75in]{geometry}

% other basic packages I load

% Sets up the title -- each document specifies the \title, \author, \course, \psnum, and \date, and \maketitle
% formats the title based on those constraints.
% TODO may want to rearrange
\newcommand{\@uthor}{\@empty}
\newcommand{\c@urse}{\@empty}
\newcommand{\psn@m}{\@empty}
\newcommand{\d@e}{\@empty}
\newcommand{\t@tle}{\@empty}
\let\@oldtitle\title   % preserves original amsart definitions
\let\@oldauthor\author
\renewcommand{\author}[1]{\renewcommand{\@uthor}{#1}}
\newcommand*{\course}[1]{\renewcommand{\c@urse}{#1}}
\newcommand*{\psnum}[1]{\renewcommand{\psn@m}{#1}}
\renewcommand*{\date}[1]{\renewcommand{\d@e}{#1}}
\renewcommand*{\title}[1]{\renewcommand{\t@tle}{#1}}

% Format title based on amsart's native title command
% TODO: will I need to place this in \AtBeginDocument?
\@oldtitle{\c@urse Homework \psn@m}
\@oldauthor{\@uthor\\\d@e}

% The header is primarily for keeping the document organized, e.g. if the pages are separated, it should be easy to
% put it back together. Options `onesided' and `twosided' determine whether the header is on each odd-numbered page
% or all pages.
\RequirePackage{fancyhdr}

% TODO I should make this uppercase (http://tex.stackexchange.com/questions/35680/uppercase-in-newcommand)
\newcommand{\he@der}{\footnotesize{\@uthor \c@urse HW\psn@m}} % Format: ARUN DEBRAY M383C HW1

\pagestyle{fancy}
\fancyfoot[C]{\footnotesize{\thepage}}
\fancyhead[L,R]{}
\ifdef\@nesided
	\fancyhead[C]{\he@der}
\else
	\fancyhead[CO]{\he@der}
\endif

\renewcommand{\headrulewidth}{0pt}

% Math macros I use. I may factor some of these out, since I use them in both lecture notes and psets.
\RequirePackage{amssymb}
\RequirePackage{mathtools}

% Shortcuts for blackboard bold math symbols
\newcommand{\N}{\m@thbb N}
\newcommand{\Z}{\m@thbb Z}
\newcommand{\Q}{\m@thbb Q}
\newcommand{\R}{\m@thbb R}
\newcommand{\C}{\m@thbb C}
\newcommand{\F}{\m@thbb F}
% allows additional user-defined symbols, e.g. \newbbsym{\P}{P} makes \P into either \mathbb{P} or \mathbf{P},
% depending on class settings. You can use \newbbsym to overwrite preexisting commands as well.
\newcommand*{\newbbsym}[2]{
	\providecommand{#1}{\@empty}
	\renewcommand{#1}{\m@thbb{#2}}
}

% Some shortcuts I use a lot
\newcommand{\e}{\varepsilon}
\newcommand{\vp}{\varphi}
\renewcommand*{\vec}[1]{\boldsymbol{\mathbf{#1}}}
\newcommand{\inj}{\hookrightarrow}
\newcommand{\surj}{\twoheadrightarrow}

% Delimiters.
% \paren and \bkt autoexpand by default, and the rest only expand if you use the starred version.
% You may disagree with this approach, but it's worked quite well for me: I use () and [] for parentheses or
% brakcets that I don't want to expand, and \paren{} and \bkt{} for those that I want to expand. However, for the
% other delimiters, I tend to use them everywhere, e.g. I'll write \abs{A_1} rather than |A_1| or \lvert A_1
% \rvert. Hence, since they generally shouldn't be expanded inline, I make the default unexpanded, with the starred
% option changing it.
\DeclarePairedDelimiter{\paren}{(}{)}
\DeclarePairedDelimiter{\set}{\{}{\}}
\DeclarePairedDelimiter{\ang}{\langle}{\rangle}
\DeclarePairedDelimiter{\abs}{\lvert}{\rvert}
\DeclarePairedDelimiter{\norm}{\lVert}{\rVert}
\DeclarePairedDelimiter{\bkt}{[}{]}
\let\@oldparen\paren
\def\paren{\@ifstar{\@oldparen}{\@oldparen*}}
\let\@oldbkt\bkt
\def\bkt{\@ifstar{\@oldbkt}{\@oldbkt*}}

% Shortcuts for calculus.
% Use \ud for integrals, e.g. \int f(x) \ud x, and \d to override spacing, e.g. \int f(x,y) \ud x\wedge\d y.
% \dfr{f}{x} typesets df/dx, and \pfr{f}{x} typesets partial f/partial x.
% TODO: better macros for higher partial derivatives.
\renewcommand{\d}{\df@nt{d}}
\newcommand{\ud}{\,\d}
\newcommand*{\dfr}[2]{\frac{\d #1}{\d #2}}
\newcommand*{\pfr}[2]{\frac{\partial #1}{\partial #2}}

% Enables a"1 as a shortcut for a^{(1)}; a"{10} is a^{(10)}. I found myself using this a lot.
\catcode`\"=13
\newcommand*{"}[1]{^{(#1)}}

% Theorems: numbered (thm, lem) and unnumbered (thm*, lem*) versions are provided. If `\thm@enum` is defined, i.e.
% if the `thminenum' option was passed, theorems are numbered within problems.
\ifdef\thm@enum
	\newtheorem{thm}{Theorem}[enumi]
\else
	\newtheorem{thm}{Theorem}
\fi
% everything else follows from that definition
\newtheorem{lem}[thm]{Lemma}
\newtheorem*{thm*}{Theorem}
\newtheorem*{lem*}{Lemma}
\newtheorem{claim}[thm]{Claim}
\newtheorem*{claim*}{Claim}

\renewcommand{\qedsymbol}{\small{\ensuremath{\boxtimes}}

% equation numbering
\ifdef\eqn@enum
	\numberwithin{equation}{enumi} % TODO in the end, it might not be numberwithin vs.
	%\renewcommand{\theequation}{\itemname . \arabic{equation}} (so that it's easier to say \item{A.1} without
	% counters
\else
	\renewcommand{\theequation}{\fnsymbol{equation}}
\fi

% TODO enumerate and spacing
